### ISSUE TITLE
Zircle and Nuxt

### ISSUE THREAD

**Issue by ripplethor** [zircleUI/zircleUI#40]
I am trying to get zircle working within nuxt.

I have managed to get it sort of working, but the issue is that when I navigate to the zircle, it comes up with "home not found"  (home being my component).

I think this maybe has something to do with routes, but given nuxt automatically creates them, I am not sure of the best way to fix this.

**Comment by tinchox5** [comment]
I ‘ve never used nuxt with zircle, but as you say the issue may be related
to routes. Can you share me a codesandbox to reproduce the issue?

**Comment by pelfed** [comment]
Hi - thanks for getting back to me.
I have created a sandbox which can be found here:
[https://codesandbox.io/s/young-hill-elrnp?file=/pages/index.vue](https://codesandbox.io/s/young-hill-elrnp?file=/pages/index.vue)

**Comment by tinchox5** [comment]
Thank you! I will try to understand what is happening

**Comment by tinchox5** [comment]
Okey! I think now is working!
I have to admit that it is a dirty hack.... I enclosed zircle into a timeout... and apparently is working.
https://codesandbox.io/s/quiet-wood-do3wu?file=/pages/index.vue

Also, I saw that you have cleared the z-canvas position...The problem is that you can't navigate back in this way. I made a wrapper and I set zircle en mixed mode.  https://zircleui.github.io/docs/api/public-api.html#config-definition

**Comment by pelfed** [comment]
Wow - thanks very much!  I set the position to unset just for the codesandbox but thanks for the info on mixed mode.

**Comment by tinchox5** [comment]
Good to know that is working! I'm currently working in a new approach that is called Zumly. If you want you can subscribe to the mailing list on https://zumly.org
