### ISSUE TITLE
How to change the size of the main circle ?

### ISSUE THREAD

**Issue by leo91000** [zircleUI/zircleUI#8]
Hello,
I am looking to change the size of the main circle. How can I achieve that ?

**Comment by tinchox5** [comment]
Hi Léo, 
In the current zircle's version, the main circle has only one size. It is not resizable. In the next version, that will be available soon,  this issue has been solved.

Meanwhile, you can do one of the following: 

1. In your Vue Instance, add the following line `this.$zircleStore.state.zircleWidth.xl = 200` <== put the size you want.  This modify the width of the main circle (`z-panel`) in the zircle's store state.  

```
mounted () {
     this.$zircleStore.state.zircleWidth.xl = 200 
  }
```

This "solution" is not responsive.  So, if you resize the browser's viewport, the size of the main circle will change again.

2. Another approach is to add a Vue hook in each view you have defined. For instance in the "home" view add the following hook:

```
updated () {
     this.$zircleStore.state.zircleWidth.xl = 200 
  }
```

This is better because is responsive and works even if you resize the viewport.

Hope that it helps you. In the next zircle's version this issue and many others are solved.

**Comment by tinchox5** [comment]
Solved by [**latest release**](https://github.com/zircleUI/zircleUI/releases/tag/v0.9.0) 
:)
